### ISSUE TITLE
ccd.detect returns empty change models on Test Data  

### ISSUE THREAD

**Issue by caffeine-potent** [USGS-EROS/lcmap-pyccd#14]
`ccd.detect` doesn't seem to be working on your test data.  

Here is the output that I'm getting:  
  
` {'algorithm': 'lcmap-pyccd:1.1.0',  
   'change_models': [],  
 'procedure': 'standard_procedure',  
 'processing_mask': array([False,  True, False,  True,  True, False, False,  True, False,  
         True,  True,  True,  True,  True, False, False, False,  True,  
        False,  True, False, False], dtype=bool)}`    
  
I would suggest reformatting the test data such that there is little chance that my _"Formatting it to make it work in python"_ is the source of error.

**Comment by caffeine-potent** [comment]
I've made a PR that makes the contents of TestData.md copy-paste-able in python.  Can someone review If my formatting is correct?  https://github.com/USGS-EROS/lcmap-pyccd/pull/15

**Comment by caffeine-potent** [comment]
I realize now that: 
  
the observation count for the sample data is 11,
while the meow_size is 12  
  
I would recommend posting better sample data.

**Comment by klsmith-usgs** [comment]
Unit testing and documentation were unfortunate victims of a short development cycle. There are plans to rectify these situations, especially as evaluation of the algorithm results is undertaken internally.

So, I would just hold on for now on this.
