### ISSUE TITLE
ratio_clear function in lcmap-pyccd/blob/develop/ccd/qa.py returns incorrect values

### ISSUE THREAD

**Issue by caffeine-potent** [USGS-EROS/lcmap-pyccd#16]
It's int-casting `count_clear_or_water(quality)/count_total(quality)`  
  
This means that a value like `0.99` evaluates to `0`, IE. The unexpected result is that everything that doesn't have 100% clear coverage is now classified as insufficient coverage.   

Quickest fix would be:

`return np.float16(count_clear_or_water(quality))/np.float16(count_total(quality))`  
  
I'll make a PR shortly.

**Comment by caffeine-potent** [comment]
I've made the PR https://github.com/USGS-EROS/lcmap-pyccd/pull/17

**Comment by klsmith-usgs** [comment]
Referencing [PEP-0238](https://www.python.org/dev/peps/pep-0238/)
The division operator was changed for Python 3 to always return a float value.

We also have no real plans to support versions earlier than 3.4. So this would include 2.7 which has an EoL set for 2020 (sooner than you might think!) as set in [PEP-373](https://www.python.org/dev/peps/pep-0373/).

Having said all that, there probably is not much of a reason against being more explicit about that operation. In which case I would probably just suggest casting one of the arguments using the ndarray.astype(float) operation. Or simpler yet would be just wrapping one in a float() call.

**Comment by caffeine-potent** [comment]
You're right. I ran the code in python 3 and got strange results. I opened up pycharm and started debugging the procedure checker to see what was going on and somehow had the interpreter set to Python 2.  I re-ran and everything seems fine
