### ISSUE TITLE
Can't get the same result using your dataset

### ISSUE THREAD

**Issue by 123helloworld123** [USGS-EROS/lcmap-pyccd#28]
Hi Kelcy Smith,

when i am running this code: https://github.com/USGS-EROS/lcmap-pyccd/blob/develop/notebooks/ccd_example.ipynb
I find i can't get the same result as you showed in this page. I am wondering why i can't get the same result even i use the default test data you used?

I still have one more question: how can i prepare my data for the CCD method? i am thinking get the scene list from Earthexplorer, and Download the dataset from ESPA. then input one pixel's time series data to this CCD method, and try to detect the break as you showed in this page: https://github.com/USGS-EROS/lcmap-pyccd/blob/develop/notebooks/ccd_example.ipynb

Thanks

**Comment by klsmith-usgs** [comment]
I had forgotten to update the example with the bug-fixes that went into effect. This has been updated on one of the branches, and will be included with the next version

Right now, that is about the best way you would have to do it. Download the data through EE, organize it similar to how some of the test data is (in memory or as a file), and then pass it in systematically. There is work being done to help with this last step.

**Comment by 123helloworld123** [comment]
Hi Kelcy Smith,

Thanks. I just find this branch: https://github.com/USGS-EROS/lcmap-pyccd/blob/feature/nt-to-dict/notebooks/ccd_example.ipynb
Is this branch you mentioned which i should use, Right? I download these code. and run this code using jupyter notebook and the data you provided ('../test/resources/test_3657_3610_observations.csv'), However, the result is only one curve, which doesn't detect the break at all and can not get the same result as you showed in this page. 

Would you mind tell me what's the possible reason that i can't get the same result as you showed in the webpage?

I really appreciate your help.

Thanks again.

**Comment by 123helloworld123** [comment]
Hi Kelcy Smith,

I tried every branch. However, the result still can not detect the break.
